server.port: 8081

resilience4j.circuitbreaker:
  instances:
    product:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      failureRateThreshold: 50
      waitInterval: 10000
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException

spring:
  cloud:
    stream:
      bindings:
        deleteFavoriteJourneyOfUser-in-0:
          destination: favoriteJourneyChannel